# Generated by Django 2.2 on 2020-05-30 19:33

import connections.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('display_name', models.CharField(max_length=999)),
                ('type', models.CharField(max_length=20)),
                ('file', models.FileField(max_length=1000, upload_to=connections.utils.upload_location, validators=[connections.utils.validate_file])),
            ],
        ),
    ]
